global using Ordering.Domain.Enums;
global using Common.CQRS;
global using Ordering.Application.DTOs;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.Models;
global using Ordering.Application.Data;
global using Ordering.Domain.ValueObjects;
global using Ordering.Application.Exceptions;