services:
    catalogdb:
        container_name: catalogdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGrES_PASSWORD=postgres
            - POSTGRES_DB=CatalogDn
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_catalog:/var/lib/postgressql/data
    